In [10]:
import numpy as np
a=np.array([[2,2],[3,2]])
print(a)
b=a.tolist()
print(b)

[[2 2]
 [3 2]]
[[2, 2], [3, 2]]


In [1]:
import numpy as np
a=([[1,3,4],[6,1,5],[1,2,1]])
r=np.trace(a)
print(r)

print(b)

3


NameError: name 'b' is not defined

In [5]:
x = np.array([[0, 1, 2], [2, 6, 7]])
b=x[x<3]
print(b)
print(x)

[0 1 2 2]
[[0 1 2]
 [2 6 7]]


In [7]:
a=([[1,2,3],[4,5,6],[1,2,4]])
b=([[1,2,3],[4,5,6],[1,2,4]])
c=np.add(a,b)
print(c)

[[ 2  4  6]
 [ 8 10 12]
 [ 2  4  8]]


In [29]:
import numpy as np
a=np.array([[1,2,3],
            [4,5,6],
            [1,2,4]])
b=(np.round(np.mean(a,axis=1)))
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [1 2 4]]
[2. 5. 2.]
